---
output:
  pdf_document: default
  word_document: default
  html_document: default
---
# CWVS: Critical Window Variable Selection

## Statistical Models
$$Y_{i}|\boldsymbol{\beta}, \boldsymbol{\alpha} \stackrel{\text{ind}}{\sim} \text{Bernoulli}\left\{p_{i}\left(\boldsymbol{\beta}, \boldsymbol{\alpha}\right)\right\},\ i=1,...,n;$$

$$\log\left\{\frac{p_{i}\left(\boldsymbol{\beta}, \boldsymbol{\alpha}\right)}{1 - p_{i}\left(\boldsymbol{\beta}, \boldsymbol{\alpha}\right)}\right\} = \textbf{x}_{i}^{\text{T}} \boldsymbol{\beta} + \sum_{j=1}^{m_{i}} \text{z}_{ij} \alpha\left(j\right);$$

$$\alpha\left(j\right)=\theta\left(j\right)\gamma\left(j\right),\ j=1,...,m;$$

$$\gamma\left(j\right)|\pi\left(j\right)\stackrel{\text{ind}}{\sim}\text{Bernoulli}\left\{\pi\left(j\right)\right\},\ \Phi^{-1}\left\{\pi\left(j\right)\right\}=\eta\left(j\right),\ j=1,...,m;$$

\[\left[\begin{array}{c}
\theta\left(j\right)  \\
\eta\left(j\right) \end{array}\right]=A\left[\begin{array}{c}
\delta_1\left(j\right)  \\
\delta_2\left(j\right) \end{array}\right],\ A=\left[\begin{array}{cc}
A_{11} & 0  \\
A_{21} & A_{22} \end{array}\right];
\]


$$\boldsymbol{\delta}_k=\left\{\delta_k\left(1\right),...,\delta_k\left(m\right)\right\}^\text{T}|\phi_k \stackrel{\text{ind}}{\sim} \text{MVN}\left\{\textbf{0}_m, \Sigma\left(\phi_k\right)\right\},\ k=1,2;$$

* $m = \max\left\{m_{i}: i=1,...,n\right\};$

* $\boldsymbol{0}_m$: Length $m$ vector with each entry equal to zero.

## Prior Information
$\beta_j \stackrel{\text{iid}}{\sim}\text{N}\left(0, \sigma^2_{\beta}\right),\ j=1,...,p;$

* $p$: Length of $\textbf{x}_{ij}$ vector (same for all $i$, $j$);

* Default setting: $\sigma^2_{\beta} = 10,000.$

$\ln\left(A_{11}\right), \ln\left(A_{22}\right), A_{21} \stackrel{\text{iid}}{\sim}\text{N}\left(0, \sigma^2_A\right)$;

* Default setting: $\sigma^2_A = 1.00.$

$\phi_k \stackrel{\text{iid}}{\sim}\text{Gamma}\left(\alpha_{\phi_k}, \beta_{\phi_k}\right),\ k=1,2;$

* Default setting: $\alpha_{\phi_k} = 1.00$, $\beta_{\phi_k} = 1.00,\ k=1,2.$

## Default Initial Values
* $\beta_j = 0$ for all $j$;

* $\gamma\left(j\right) = 1$ for all $j$;

* $\delta_{k}\left(j\right) = 0$ for all $j$, $k$;

* $\phi_k = -\ln\left(0.05\right)/\left(m - 1\right)$ for all $k$;

* $A_{kk} = 1$ for all $k$;

* $A_{21} = 0$.

## Alternate Likelihood: Gaussian
$Y_i|\boldsymbol{\beta}, \boldsymbol{\alpha}, \sigma^2_{\epsilon} \stackrel{\text{ind}}{\sim} \text{Normal}\left(\textbf{x}_{i}^{\text{T}} \boldsymbol{\beta} + \sum_{j=1}^{m_{i}} \text{z}_{ij} \alpha\left(j\right), \sigma^2_{\epsilon}\right),\ i=1,...,n.$

* $\sigma^2_{\epsilon} \sim \text{Inverse Gamma}\left(a_{\sigma^2_{\epsilon}}, b_{\sigma^2_{\epsilon}}\right);$ 

* Default setting: $a_{\sigma^2_{\epsilon}} = 0.01$, $b_{\sigma^2_{\epsilon}} = 0.01$; 

* Default initial value: $\sigma^2_{\epsilon} = 1.00$.

## Alternate Likelihood: Negative Binomial
$Y_i|\boldsymbol{\beta}, \boldsymbol{\alpha}, r \stackrel{\text{ind}}{\sim} \text{Negative Binomial}\left\{r, \lambda_i\left(\boldsymbol{\beta}, \boldsymbol{\theta}\right)\right\},\ i=1,...,n;$

$\text{ln}\left\{\frac{\lambda_i\left(\boldsymbol{\beta}, \boldsymbol{\alpha}\right)}{1 - \lambda_i\left(\boldsymbol{\beta}, \boldsymbol{\alpha}\right)}\right\} = \text{O}_i + \textbf{x}_{i}^{\text{T}} \boldsymbol{\beta} + \sum_{j=1}^{m_{i}} \text{z}_{ij} \alpha\left(j\right).$

* $r \sim \text{Discrete Uniform}\left[a_r, b_r\right];$ 

* Default setting: $a_r = 1$, $b_r = 100$; 

* Default initial value: $r = b_r$.

## Likelihood Indicator
* likelihood_indicator $= 0$: Bernoulli; 

* likelihood_indicator $= 1$: Gaussian;

* likelihood_indicator $= 2$: Negative binomial.
