---
output:
  word_document: default
  pdf_document: default
  html_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# CWVS: Critical Window Variable Selection
## CWVS_Example

[1] Simulate data for analysis:

* Setting the reproducibility seed and initializing packages for data simulation:
```{r}
set.seed(4679)
library(CWVS)
library(boot)  #Inverse logit transformation
```

* Setting the global data values:
```{r}
n<-5000  #Sample size
m<-27  #Number of exposure time periods
x<-matrix(1,
nrow=n,
ncol=1)  #Covariate design matrix
z<-matrix(rnorm(n=(n*m)),
nrow=n,
ncol=m)  #Exposure design matrix
for(j in 1:m){
z[,j]<-(z[,j] - median(z[,j]))/IQR(z[,j])  #Data standardization (interquartile range)
}
```

* Setting the values for the statistical model parameters:
```{r}
beta_true<- -0.30
theta_true<-rep(0.60, times=m)
gamma_true<-c(rep(0, times=12),
rep(1, times=4),
rep(0, times=11))
alpha_true<-gamma_true*theta_true
logit_p_true<-x%*%beta_true +
z%*%alpha_true
probs_true<-inv.logit(logit_p_true)
hist(probs_true)
```

* Simulating the analysis dataset:
```{r echo=TRUE}
y<-rbinom(n=n, 
          size=1, 
          prob=probs_true)
```

[2] Fit CWVS to identify/estimate critical windows of susceptibility:

```{r echo=TRUE}
results<-CWVS(mcmc_samples = 10000,
              y = y, x = x, z = z,
              metrop_var_phi1_trans = 1.00,
              metrop_var_phi2_trans = 1.00,
              metrop_var_A11_trans = 0.05,
              metrop_var_A22_trans = 0.50,
              metrop_var_A21 = 1.00)

plot(results$beta[1, 1001:10000],
     type="l",
     ylab="beta",
     xlab="Sample")
abline(h=beta_true,
       col="red",
       lwd=2)  #True value
plot(rowMeans(results$alpha[,1001:10000]),
              pch=16,
              ylab="alpha",
              xlab="Time")
points(alpha_true, 
       col="red")
plot(rowMeans(results$gamma[,1001:10000]),
     pch=16,
     ylab="gamma",
     xlab="Time")
points(gamma_true, 
       col="red")
```
