---
output:
  word_document: default
  html_document: default
  pdf_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# GPCW: Gaussian Process Model for Critical Window Estimation

## GPCW_Example

[1] Simulate data from the proposed model:

* Setting the reproducibility seed and initializing packages for data simulation: 
```{r}
set.seed(8453)

library(GPCW)  
library(mnormt)  #Multivariate normal distribution
library(boot)  #Inverse logit transformation
```

* Setting the global data values:
```{r}
n<-5000  #Sample size
m<-36  #Number of exposure time periods
x<-matrix(1, 
          nrow=n, 
          ncol=1)  #Covariate design matrix
z<-matrix(rnorm(n=(n*m)), 
          nrow=n, 
          ncol=m)  #Exposure design matrix

for(j in 1:m){
   z[,j]<-(z[,j] - median(z[,j]))/IQR(z[,j])  #Data standardization (interquartile range)
   }
```

* Setting the values for the statistical model parameters:
```{r}
beta_true<- -0.30
sigma2_theta_true<-0.50
phi_true<-0.01
Sigma_true<-sigma2_theta_true*chol2inv(chol(temporal_corr_fun(m, 
                                                              phi_true)[[1]]))
theta_true<-rmnorm(n=1, 
                   mean=rep(0, times=m), 
                   varcov=Sigma_true)
theta_true<-theta_true - mean(theta_true)
logit_p_true<-x%*%beta_true + 
              z%*%theta_true
probs_true<-inv.logit(logit_p_true)
hist(probs_true)
```

* Simulating the analysis dataset:
```{r}
y<-rbinom(n=n, 
          size=1, 
          prob=probs_true)
```

[2] Fit GPCW to estimate critical windows of susceptibility:

```{r echo=TRUE}
results<-GPCW(mcmc_samples = 10000,
              y = y, x = x, z = z,
              metrop_var_phi_trans = 1.15)
```

[3]  Analyzing Output:

```{r}
par(mfrow=c(2,2))
plot(results$beta[1, 1001:10000], 
     type="l",
     ylab="beta",
     xlab="Sample")
abline(h=beta_true,
       col="red",
       lwd=2)  #True value
plot(results$sigma2_theta[1001:10000],
     type="l",
     ylab="sigma2_theta",
     xlab="Sample")
abline(h=sigma2_theta_true,
       col="red",
       lwd=2)  #True value
plot(results$phi[1001:10000],
     type="l",
     ylab="phi",
     xlab="Sample")
abline(h=phi_true, 
       col="red",
       lwd=2)  #True value
plot(rowMeans(results$theta[,1001:10000]), 
     pch=16,
     ylab="theta",
     xlab="Time")
points(theta_true, 
       pch=16, 
       col="red")  #True values
```