# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

A11_update <- function(A11_old, x, z, w, gamma_l, beta, gamma, delta1, sigma2_A, metrop_var_A11_trans, acctot_A11_trans) {
    .Call(`_CWVS_A11_update`, A11_old, x, z, w, gamma_l, beta, gamma, delta1, sigma2_A, metrop_var_A11_trans, acctot_A11_trans)
}

A21_update <- function(A21_old, gamma_star, delta1, A22, delta2, sigma2_A, metrop_var_A21, acctot_A21) {
    .Call(`_CWVS_A21_update`, A21_old, gamma_star, delta1, A22, delta2, sigma2_A, metrop_var_A21, acctot_A21)
}

A22_update <- function(A22_old, gamma_star, delta1, A21_old, delta2, sigma2_A, metrop_var_A22_trans, acctot_A22_trans) {
    .Call(`_CWVS_A22_update`, A22_old, gamma_star, delta1, A21_old, delta2, sigma2_A, metrop_var_A22_trans, acctot_A22_trans)
}

beta_update <- function(x, z, sigma2_beta, w, gamma_l, gamma_old, A11_old, delta1_old) {
    .Call(`_CWVS_beta_update`, x, z, sigma2_beta, w, gamma_l, gamma_old, A11_old, delta1_old)
}

CWVS <- function(mcmc_samples, y, x, z, metrop_var_phi1_trans, metrop_var_phi2_trans, metrop_var_A11_trans, metrop_var_A22_trans, metrop_var_A21, sigma2_beta_prior = NULL, alpha_phi1_prior = NULL, beta_phi1_prior = NULL, alpha_phi2_prior = NULL, beta_phi2_prior = NULL, sigma2_A_prior = NULL, beta_init = NULL, gamma_init = NULL, delta1_init = NULL, delta2_init = NULL, phi1_init = NULL, phi2_init = NULL, A11_init = NULL, A22_init = NULL, A21_init = NULL) {
    .Call(`_CWVS_CWVS`, mcmc_samples, y, x, z, metrop_var_phi1_trans, metrop_var_phi2_trans, metrop_var_A11_trans, metrop_var_A22_trans, metrop_var_A21, sigma2_beta_prior, alpha_phi1_prior, beta_phi1_prior, alpha_phi2_prior, beta_phi2_prior, sigma2_A_prior, beta_init, gamma_init, delta1_init, delta2_init, phi1_init, phi2_init, A11_init, A22_init, A21_init)
}

delta1_update <- function(x, z, w, gamma_l, beta, gamma, gamma_star, A11_old, A21_old, A22_old, delta2_old, corr_inv1) {
    .Call(`_CWVS_delta1_update`, x, z, w, gamma_l, beta, gamma, gamma_star, A11_old, A21_old, A22_old, delta2_old, corr_inv1)
}

delta2_update <- function(gamma_star, delta1, A21_old, A22_old, corr_inv2) {
    .Call(`_CWVS_delta2_update`, gamma_star, delta1, A21_old, A22_old, corr_inv2)
}

gamma_star_update <- function(gamma, delta1_old, A21_old, A22_old, delta2_old) {
    .Call(`_CWVS_gamma_star_update`, gamma, delta1_old, A21_old, A22_old, delta2_old)
}

gamma_update <- function(x, z, w, gamma_l, beta, gamma_old, A11_old, delta1_old, A21_old, A22_old, delta2_old) {
    .Call(`_CWVS_gamma_update`, x, z, w, gamma_l, beta, gamma_old, A11_old, delta1_old, A21_old, A22_old, delta2_old)
}

neg_two_loglike_update <- function(y, x, z, beta, gamma, A11, delta1) {
    .Call(`_CWVS_neg_two_loglike_update`, y, x, z, beta, gamma, A11, delta1)
}

phi_update <- function(phi_old, delta, temporal_corr_info, alpha_phi, beta_phi, metrop_var_phi_trans, acctot_phi_trans) {
    .Call(`_CWVS_phi_update`, phi_old, delta, temporal_corr_info, alpha_phi, beta_phi, metrop_var_phi_trans, acctot_phi_trans)
}

rcpp_pgdraw <- function(b, c) {
    .Call(`_CWVS_rcpp_pgdraw`, b, c)
}

temporal_corr_fun <- function(p_z, phi) {
    .Call(`_CWVS_temporal_corr_fun`, p_z, phi)
}

w_update <- function(y, x, z, beta_old, gamma_old, A11_old, delta1_old) {
    .Call(`_CWVS_w_update`, y, x, z, beta_old, gamma_old, A11_old, delta1_old)
}

