# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

A11_update <- function(A11_old, x, z, off_set, w, gamma_l, beta, gamma, delta1, sigma2_A, metrop_var_A11_trans, acctot_A11_trans) {
    .Call(`_CWVS_A11_update`, A11_old, x, z, off_set, w, gamma_l, beta, gamma, delta1, sigma2_A, metrop_var_A11_trans, acctot_A11_trans)
}

A21_update <- function(gamma_star, delta1, A22, delta2, sigma2_A) {
    .Call(`_CWVS_A21_update`, gamma_star, delta1, A22, delta2, sigma2_A)
}

A22_update <- function(A22_old, gamma_star, delta1, A21_old, delta2, sigma2_A, metrop_var_A22_trans, acctot_A22_trans) {
    .Call(`_CWVS_A22_update`, A22_old, gamma_star, delta1, A21_old, delta2, sigma2_A, metrop_var_A22_trans, acctot_A22_trans)
}

CWVS <- function(mcmc_samples, y, x, z, likelihood_indicator, metrop_var_phi1_trans, metrop_var_phi2_trans, metrop_var_A11_trans, metrop_var_A22_trans, offset = NULL, a_r_prior = NULL, b_r_prior = NULL, a_sigma2_epsilon_prior = NULL, b_sigma2_epsilon_prior = NULL, sigma2_beta_prior = NULL, alpha_phi1_prior = NULL, beta_phi1_prior = NULL, alpha_phi2_prior = NULL, beta_phi2_prior = NULL, sigma2_A_prior = NULL, r_init = NULL, sigma2_epsilon_init = NULL, beta_init = NULL, gamma_init = NULL, delta1_init = NULL, delta2_init = NULL, phi1_init = NULL, phi2_init = NULL, A11_init = NULL, A22_init = NULL, A21_init = NULL) {
    .Call(`_CWVS_CWVS`, mcmc_samples, y, x, z, likelihood_indicator, metrop_var_phi1_trans, metrop_var_phi2_trans, metrop_var_A11_trans, metrop_var_A22_trans, offset, a_r_prior, b_r_prior, a_sigma2_epsilon_prior, b_sigma2_epsilon_prior, sigma2_beta_prior, alpha_phi1_prior, beta_phi1_prior, alpha_phi2_prior, beta_phi2_prior, sigma2_A_prior, r_init, sigma2_epsilon_init, beta_init, gamma_init, delta1_init, delta2_init, phi1_init, phi2_init, A11_init, A22_init, A21_init)
}

beta_update <- function(x, z, off_set, sigma2_beta, w, gamma_l, gamma_old, A11_old, delta1_old) {
    .Call(`_CWVS_beta_update`, x, z, off_set, sigma2_beta, w, gamma_l, gamma_old, A11_old, delta1_old)
}

delta1_update <- function(x, z, off_set, w, gamma_l, beta, gamma, gamma_star, A11_old, A21_old, A22_old, delta2_old, corr_inv1) {
    .Call(`_CWVS_delta1_update`, x, z, off_set, w, gamma_l, beta, gamma, gamma_star, A11_old, A21_old, A22_old, delta2_old, corr_inv1)
}

delta2_update <- function(gamma_star, delta1, A21_old, A22_old, corr_inv2) {
    .Call(`_CWVS_delta2_update`, gamma_star, delta1, A21_old, A22_old, corr_inv2)
}

exp_rs <- function(a, b) {
    .Call(`_CWVS_exp_rs`, a, b)
}

gamma_star_update <- function(gamma, delta1_old, A21_old, A22_old, delta2_old) {
    .Call(`_CWVS_gamma_star_update`, gamma, delta1_old, A21_old, A22_old, delta2_old)
}

gamma_update <- function(x, z, off_set, w, gamma_l, beta, gamma_old, A11_old, delta1_old, A21_old, A22_old, delta2_old) {
    .Call(`_CWVS_gamma_update`, x, z, off_set, w, gamma_l, beta, gamma_old, A11_old, delta1_old, A21_old, A22_old, delta2_old)
}

half_norm_rs <- function(a, b) {
    .Call(`_CWVS_half_norm_rs`, a, b)
}

neg_two_loglike_update <- function(y, x, z, off_set, likelihood_indicator, r, sigma2_epsilon, beta, gamma, A11, delta1) {
    .Call(`_CWVS_neg_two_loglike_update`, y, x, z, off_set, likelihood_indicator, r, sigma2_epsilon, beta, gamma, A11, delta1)
}

norm_rs <- function(a, b) {
    .Call(`_CWVS_norm_rs`, a, b)
}

phi_update <- function(phi_old, delta, temporal_corr_info, alpha_phi, beta_phi, metrop_var_phi_trans, acctot_phi_trans) {
    .Call(`_CWVS_phi_update`, phi_old, delta, temporal_corr_info, alpha_phi, beta_phi, metrop_var_phi_trans, acctot_phi_trans)
}

r_update <- function(y, x, z, off_set, a_r, b_r, beta, gamma, A11, delta1) {
    .Call(`_CWVS_r_update`, y, x, z, off_set, a_r, b_r, beta, gamma, A11, delta1)
}

rcpp_pgdraw <- function(b, c) {
    .Call(`_CWVS_rcpp_pgdraw`, b, c)
}

rnorm_trunc <- function(mu, sigma, lower, upper) {
    .Call(`_CWVS_rnorm_trunc`, mu, sigma, lower, upper)
}

sigma2_epsilon_update <- function(a_sigma2_epsilon, b_sigma2_epsilon, y, x, z, beta_old, gamma_old, A11_old, delta1_old) {
    .Call(`_CWVS_sigma2_epsilon_update`, a_sigma2_epsilon, b_sigma2_epsilon, y, x, z, beta_old, gamma_old, A11_old, delta1_old)
}

temporal_corr_fun <- function(p_z, phi) {
    .Call(`_CWVS_temporal_corr_fun`, p_z, phi)
}

unif_rs <- function(a, b) {
    .Call(`_CWVS_unif_rs`, a, b)
}

w_update <- function(y, x, z, off_set, likelihood_indicator, r, beta_old, gamma_old, A11_old, delta1_old) {
    .Call(`_CWVS_w_update`, y, x, z, off_set, likelihood_indicator, r, beta_old, gamma_old, A11_old, delta1_old)
}

